---
# tasks file for ansible-role-wordpress

- name: Inclusion des t창ches d'installation des paquets
  ansible.builtin.include_tasks: install.yml

- name: Inclusion des t창ches MariaDB
  ansible.builtin.include_tasks: mariadb.yml

- name: Inclusion des t창ches WordPress
  ansible.builtin.include_tasks: wordpress.yml

- name: Inclusion des t창ches Apache
  ansible.builtin.include_tasks: apache.yml
